name: Continuous Integration

on:
  push:
    branches: [ master ]
    paths-ignore:
      - README.md
      - images/**/*
      - .run/**/*
  pull_request:
    branches: [ master ]
    types: [ opened, reopened, synchronize, edited ]
    paths-ignore:
      - README.md
      - LICENSE
      - iac

env:
  node_version: "16"
  tf_version: "1.2.2"
  aws_account: "113609878794"
  aws_gha_role: byu-wabs-oauth-prd-gha

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.node_version }}

      - name: Install Node Dependencies
        run: npm install

      - name: Lint
        run: npm run lint

  test:
    name: Test
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: read
      pull-requests: write
      id-token: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: "arn:aws:iam::${{ env.aws_account }}:role/${{ env.aws_gha_role }}"
          role-session-name: ${{ github.sha }}
          aws-region: us-west-2

      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.node_version }}

      - name: Install Node Dependencies
        run: npm install

      - name: Test
        run: npm test

  terraform-format:
    name: Terraform Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Terraform Setup
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ env.tf_version }}

      - name: Terraform Format
        run: terraform fmt -check -recursive
